#:schema node_modules/wrangler/config-schema.json
name = "amanai"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[vars]
OPENAI_LIKE_API_BASE_URL = "https://kaggle-ai-proxy.myfaltuhere786.workers.dev/v1"
OPENAI_LIKE_API_KEY = "sk-no-key"
OPENAI_LIKE_API_MODELS = "qwen3.6-35b-aggressive:8192"

